Correção ortográfica
piratarialink/megathread_pirata pull request #16
Opened 2024-10-29 01:00 UTC by carryingwater

2024-11-02 13:55 UTC, carryingwater commented
@augustresende

2024-11-03 16:37 UTC, augustresende requested changes

2024-11-03 16:37 UTC, augustresende commented on docs/filmes-tv.md
> +- ✔️ Todos os links foram analisados ​​e aprovados pelos moderadores, mas prossiga com cautela.
por favor reverta essa mudança e resolva conflitos

2024-11-03 16:37 UTC, augustresende commented on docs/ferramentas.md
> +- ✔️ Todos os links foram analisados ​​e aprovados pelos moderadores, mas prossiga com cautela.
por favor reverta essa mudança

2024-11-04 16:47 UTC, suportefloripa approved these changes
correções de links e ortografia

2024-11-07 02:00 UTC, carryingwater commented
Feito e refeito! (De novo)

Novos links:

- https://www.invitehawk.com/trackerlist/
- https://github.com/A-SunsetMkt-Forks/Tampermonkey-Script/blob/main/Unlimited_downloader.js
- [megasoft1.com](https://megasoft1.com/)
- https://t.me/reverse_image_search_bot
- https://t.me/anotherLeakOSINTrobotbot?start=DXQ0pV2
- https://fileriver.net/: [SCUMWARE é falso positvo](https://www.reddit.com/r/antivirus/comments/vb2751/comment/ic5y508/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) - [Fortinet é falso positivo](https://www.reddit.com/r/Malware/comments/5l4rg8/it_has_now_been_over_3_months_since_fortinet/) - [CRDF é falso positivo](https://www.reddit.com/r/techsupport/comments/jnwyez/comment/gb45rgx/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button).
- https://embehub.com/
- https://www.tubedigger.com/
- https://github.com/matheusbach/legen

Aproveitei e já inseri as atualizações do PR #17 e #18:

• Novos Trackers:

-[Tracker2.Postman](http://tracker2.postman.i2p) 

-[Linuxtracker](linuxtracker.org) 

-[Extremlymtorrents](extremlymtorrents.ws) 

-[Sktorrent](sktorrent.org) 

-[Digitalcore](https://digitalcore.club/signup/)

2024-11-08 22:13 UTC, augustresende approved these changes

2024-11-08 22:14 UTC, merged